### ISSUE TITLE
Expose internal modules

### ISSUE THREAD

**Issue by choener** [haskell-numerics/hmatrix#235]
Please expose the internal modules, especially the data constructors for Matrix.

**Comment by Alexander-Ignatyev** [comment]
Have you checked function exported in https://hackage.haskell.org/package/hmatrix-0.18.1.0/docs/Numeric-LinearAlgebra-Devel.html?

**Comment by choener** [comment]
Yes, I'd like direct access to the data constructor and the accessor functions like ```xdat```.

I have no idea if I'd like to use functions from, say, ```Internal.LAPACK''' ... but I think I will want to.

**Comment by albertoruiz** [comment]
In addition to the tools in Numeric.LinearAlgebra.Devel, you also have `flatten`, which gives you the data vector, similar to `xdat` but guaranteed to be in row order, and `reshape`, which creates a matrix from a vector, checking the number of elements. Perhaps such "smart" accesor and constructor can be useful for you.

**Comment by choener** [comment]
Thanks, but ```flatten''' will in certain cases create a temporary matrix, I assume? It would be really more convenient to have direct access to these function / constructors. And there is not really a downside, and the upside is a lot more convenience for special cases.

**Comment by Alexander-Ignatyev** [comment]
Have you considered to use 

```
apply :: Matrix t -> (b -> IO r) -> Trans (Matrix t) b -> IO r
```

where ` Trans (Matrix t) b`  should be `(CInt -> CInt -> CInt -> CInt -> Ptr t -> f)`?

and `Ptr a` is a pointer to underlying array.

**Comment by choener** [comment]
All of these approaches are very much inferior to, for example, ```f . xdat``` (which also allows using the whole vector package for all functions ```f```).

I'm a bit confused as to what the problem with exposing the underlying structure is.

**Comment by albertoruiz** [comment]
The internal constructor is hidden to avoid the creation of invalid structures. 

Equal matrices may have different `xdat` vectors (because of having different data orders, as internal memory transposition can sometimes be avoided, or because they are slices and some elements are unused). Just using `xdat` loses information. `flatten` gives you a "clean" vector to be used with the vector package.

I recommend that you first try the available development and data manipulation tools, as well as the simple `flatten` / `reshape` approach, to check if you get reasonable performance. If there is a clear use case that needs the internal structure we can expose it.

**Comment by mbwgh** [comment]
On the other hand, exposing `.Internal` modules is a well-established practice by now, and people know that importing those will void their warranty. Library authors export them because some unforeseeable use-case might pop up in the future. Having the usual warnings in-place, what does trying to protect the users from themselves still buy us? If I accidentally create some data that should not have been representable, I know it's my own fault.

I don't think exporting the internals warrants a use case, really. It doesn't really hurt the library maintainer (unless I am missing something obvious here), and we can assume the user to be grown-up.
Furthermore, this would make it a little easier to play around with the library, without having to clone the source.

One use-case I can come up with off the top of my hat after all is things like `Generic` instances, which you can not define manually and for which you need the constructors in scope. While this may not be the most fitting example for `hmatrix`, I did encounter this kind of situation a few times in my applications (serialization, for instance) and being able to import an `.Internal` module saved me a lot of time.

**Comment by nh2** [comment]
Fixed by commit https://github.com/haskell-numerics/hmatrix/commit/6b99302a340819e8ed0c8a4c4756933ee6173cdc

**Comment by Mikolaj** [comment]
Thank you!

**Comment by nh2** [comment]
(Note I didn't implement that, I only noticed it and am am posting it here so that somebody can close this issue :) )

**Comment by idontgetoutmuch** [comment]
I will close it in that case - thanks
